server:
  port: 8080

spring:
  mvc:
#    view:
#      prefix: /templates/
#      suffix: .html
    #  静态资源放行
    static-path-pattern: /static/**
#    配置静态资源的路径
#  resources:
#    static-locations: classpath:/static/

  thymeleaf:
    # 引入spring-boot-starter-thymeleaf后，默认会从/templates/下寻找对应html；静态目录也变为/templates/
    # thymeleaf默认路径(匹配比较严格，尾缀需加/)
    prefix: classpath:/templates/
    # 开发阶段缓存设置为false;正式使用应该为true
    cache: false

  #启用热部署
  devtools:
    restart:
      enabled: true
  #关于热部署
    #修改类–>保存：应用会重启
    #修改配置文件–>保存：应用会重启
    #修改页面–>保存：应用不会重启，但会重新加载，页面会刷新（原理是将spring.thymeleaf.cache设为false，参考:Spring Boot配置模板引擎）

#  数据库
  datasource:
    # nas
    url: jdbc:mariadb://192.168.1.90:3306/springboot_community_project
    username: root
    password: zou9RYdAGW2MKoBY

    # remote gcp
#    url: jdbc:mariadb://localhost:3306/springboot_community_project
#    username: second
#    password: 9Zl0TffnlsL0

    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 580000

  # redis配置
  redis:
    host: 192.168.1.90
    port: 6379
    password: MuMD02Hov6Xk
    jedis:
      pool:
        max-active: 8   # 连接池最大空闲
        min-idle: 0     # 最小
        max-wait: -1    # 连接超时,负值为无限制
    timeout: 3000          # 等待超时

#github服务器端的配置
github:
  client_id: Iv1.2299807260a02e0e
  cli ent_secret: b0500db3906303de1ab10cca68da8e33b7ad1b64
  code: null
  redirect_uri: http://cloud1701.myqnapcloud.com:28080/callback
#  redirect_uri: http://localhost:8080/callback
  state: null

#ftp上传地址配置
ftp:
  ip: 192.168.1.90
  user: onlyForFtp
  password: H%5Ytp&t6b$^28


#log日志，path为根目录
  #logging:
  #  file: logging.log
  #  path: /


file:
  staticAccessPath: /upload/**
  ##linux path    ①nas；只适用于ftp上传
#  uploadFolder: /share/homes/onlyForFtp/upload/
#                ②docker；推荐
  uploadFolder: /home/share/upload/

  ##windows path desktop
#  uploadFolder: E://Code/Java/SpringBoot_Project_Community/target/classes/static/upload/
  ##windows path note
#  uploadFolder: D://Code/JAVA/SpringBoot_Project_Community/target/classes/static/upload
