spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    ##  静态资源放行
    static-path-pattern: /static/**

  #缓存设置为false, 这样修改之后马上生效，便于调试
  thymeleaf:
    cache: false


#启用热部署
  devtools:
    restart:
      enabled: true
  #关于热部署
    #修改类–>保存：应用会重启
    #修改配置文件–>保存：应用会重启
    #修改页面–>保存：应用不会重启，但会重新加载，页面会刷新（原理是将spring.thymeleaf.cache设为false，参考:Spring Boot配置模板引擎）


#  数据库信息
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/springboot_community_project?serverTimezone=UTC
      username: root
      password: 111111



#github服务器端的配置
github:
    client_id: Iv1.2299807260a02e0e
    cli ent_secret: b0500db3906303de1ab10cca68da8e33b7ad1b64
    code: null
    redirect_uri: http://localhost:8080/callback
    state: null




